version: '3'

tasks:
  setup:
    desc: Setup the project
    cmds:
      - lefthook install -f

  mod:
    cmds:
      - go mod download
      - go mod tidy

  lint:
    desc: Run linters
    sources:
      - './**/*.go'
      - .golangci.yaml
    cmd: ./.build/golangci-lint run

  lint:fix:
    desc: Run linters and fix issues
    sources:
      - './**/*.go'
      - .golangci.yaml
    cmd: ./.build/golangci-lint run --fix

  fmt:go:
    desc: Format go files
    sources:
      - './**/*.go'
    cmd: gofumpt -w .

  fmt:sql:
    desc: Format sql files
    sources:
      - './**/*.sql'
    cmd: prettier --write .

  test:
    desc: Run tests
    sources:
      - './**/*.go'
    cmd: go test -race -count=1 ./...
