// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PasswordResetToken struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	IsUsed    bool
	Token     string
	ExpiresAt pgtype.Timestamp
	UserID    pgtype.UUID
}

type User struct {
	ID              pgtype.UUID
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Email           string
	IsEmailVerified bool
	FirstName       *string
	LastName        *string
}

type UserCredential struct {
	ID                   pgtype.UUID
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	Name                 string
	UserID               pgtype.UUID
	UserCredentialKey    string
	UserCredentialSecret string
}

type UserEmailVerificationToken struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	IsUsed    bool
	Token     string
	Email     string
	UserID    pgtype.UUID
}

type UserSession struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
	UserID    pgtype.UUID
	EvictedBy pgtype.UUID
}
