// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: session_query.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (id, user_id, expires_at)
VALUES ($1::UUID, $2::UUID, $3)
RETURNING id
`

type CreateUserSessionParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUserSession, arg.ID, arg.UserID, arg.ExpiresAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const expireAllSessionsByUserID = `-- name: ExpireAllSessionsByUserID :many
UPDATE user_sessions
SET expires_at = NOW()
WHERE user_id = $1::UUID
RETURNING id
`

func (q *Queries) ExpireAllSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, expireAllSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireSessionByID = `-- name: ExpireSessionByID :one
UPDATE user_sessions SET expires_at = NOW() WHERE id = $1::UUID RETURNING id
`

func (q *Queries) ExpireSessionByID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, expireSessionByID, id)
	err := row.Scan(&id)
	return id, err
}

const findUserSessionByID = `-- name: FindUserSessionByID :one
SELECT id, created_at, updated_at, expires_at, user_id, evicted_by
FROM user_sessions
WHERE id = $1::UUID AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) FindUserSessionByID(ctx context.Context, id pgtype.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, findUserSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.EvictedBy,
	)
	return i, err
}
